import os

data = [
    {"id": "Q040", "tema": "Valutazione Quantitativa", "q": "Per user experience / esperienza d'uso si intende...", "a": "Ciò che una persona prova prima, durante e dopo l'utilizzo di un prodotto o sistema. Ha natura soggettiva (riguarda pensieri e percezioni individuali) ed è dinamica (si modifica nel tempo). Oltre all'usabilità, include affettività, emozione e l'attribuzione di senso e valore.", "kb": "[[UX - User Experience]]", "tag": "ium flashcard valutazione-quantitativa ux"},
    {"id": "Q041", "tema": "Valutazione Quantitativa", "q": "Quali dimensioni sono comprese nella deﬁnizione di usabilità secondo lo standard ISO 9241?", "a": "Le tre dimensioni fondamentali sono: Efficacia (capacità di raggiungere l'obiettivo o tasso di successo/errori), Efficienza (risorse spese per raggiungere l'obiettivo, es. tempo o numero di clic) e Soddisfazione (gradimento e comfort nell'uso).", "kb": "[[Usabilità]]", "tag": "ium flashcard valutazione-quantitativa usabilita"},
    {"id": "Q042", "tema": "Valutazione Quantitativa", "q": "Per robustezza di un sistema interattivo si intende...", "a": "La capacità del sistema di supportare l'utente nel prevenire errori o correggerli facilmente. Un sistema robusto induce un basso tasso di errori critici e garantisce un basso impatto negativo in caso di errore.", "kb": "[[Robustezza]]", "tag": "ium flashcard valutazione-quantitativa robustezza"},
    {"id": "Q043", "tema": "Valutazione Quantitativa", "q": "La ricordabilità di un sistema interattivo riguarda...", "a": "La facilità con cui un utente occasionale riacquista la competenza necessaria per usare il sistema dopo un certo periodo di inutilizzo, senza dover imparare nuovamente le procedure da zero.", "kb": "[[Ricordabilità]]", "tag": "ium flashcard valutazione-quantitativa ricordabilita"},
    {"id": "Q044", "tema": "Valutazione Quantitativa", "q": "L'ipotesi nulla di un test ipotesi...", "a": "È l'ipotesi di base assunta vera in partenza. Solitamente prevede che NON ci sia differenza significativa tra due sistemi A e B, o che non ci sia effetto dovuto alla variabile indipendente manipolata.", "kb": "[[Test statistici per IUM]]", "tag": "ium flashcard statistica ipotesi-nulla"},
    {"id": "Q045", "tema": "Valutazione Quantitativa", "q": "In statistica inferenziale il livello di signiﬁcatività osservato è...", "a": "È il p-value. Indica la probabilità di osservare i dati effettivamente raccolti (o valori ancora più estremi) qualora l'ipotesi nulla H0 fosse vera. Attenzione a non confonderlo con alfa (livello di significatività fissato a priori).", "kb": "[[Significativita statistica e pratica]]", "tag": "ium flashcard statistica p-value"},
    {"id": "Q046", "tema": "Valutazione Quantitativa", "q": "In statistica inferenziale, alfa è...", "a": "Il livello di significatività fissato a priori (solitamente 0.05). Rappresenta il rischio massimo che siamo disposti a correre di rigettare l'ipotesi nulla quando in realtà è vera (commettere un errore di falso positivo o di Tipo I).", "kb": "[[Significativita statistica e pratica]]", "tag": "ium flashcard statistica alfa"},
    {"id": "Q047", "tema": "Valutazione Quantitativa", "q": "In un test statistico per usabilità fare una predizione a due code è indicato quando...", "a": "Si vuole semplicemente capire se i due sistemi A e B sono diversi, senza assumere o ipotizzare a priori quale dei due produrrà il risultato migliore o peggiore.", "kb": "[[Test statistici per IUM]]", "tag": "ium flashcard statistica a-due-code"},
    {"id": "Q048", "tema": "Valutazione Quantitativa", "q": "Il p-value (o livello di signiﬁcatività osservato) è la probabilità di...", "a": "Raccogliere dati uguali a quelli appena raccolti nel campione (o ancora più estremi) supponendo che l'ipotesi nulla H0 sia vera.", "kb": "[[Significativita statistica e pratica]]", "tag": "ium flashcard statistica p-value"},
    {"id": "Q049", "tema": "Valutazione Quantitativa", "q": "Se il p-value di un test è basso, signiﬁca che...", "a": "È altamente improbabile che la differenza osservata nei dati sia dovuta solo al caso se l'ipotesi nulla fosse vera. Se il p-value è inferiore ad alfa, rigettiamo l'ipotesi nulla e accettiamo l'ipotesi alternativa.", "kb": "[[Significativita statistica e pratica]]", "tag": "ium flashcard statistica p-value"},
    {"id": "Q050", "tema": "Valutazione Quantitativa", "q": "Quando si può rigettare l'ipotesi nulla?", "a": "Quando il livello di significatività osservato (p-value) è rigorosamente inferiore al livello di significatività prefissato a priori (alfa), ad esempio il 5% (0.05).", "kb": "[[Significativita statistica e pratica]]", "tag": "ium flashcard statistica ipotesi-nulla"},
    {"id": "Q051", "tema": "Valutazione Quantitativa", "q": "In un test utente, calcolare il tempo necessario ad eseguire un compito correttamente è una misura di...", "a": "Efficienza (le risorse e lo sforzo impiegati dall'utente per raggiungere lo scopo).", "kb": "[[Efficienza]], [[Usabilità]]", "tag": "ium flashcard valutazione-quantitativa efficienza"},
    {"id": "Q052", "tema": "Valutazione Quantitativa", "q": "In un test utente, il rapporto dei compiti eseguiti correttamente e quelli non eseguiti è una misura di...", "a": "Efficacia (la percentuale di successo nel completamento dell'obiettivo).", "kb": "[[Efficacia]], [[Usabilità]]", "tag": "ium flashcard valutazione-quantitativa efficacia"},
    {"id": "Q053", "tema": "Valutazione Quantitativa", "q": "Una scala Likert è una scala dove i valori...", "a": "Sono di tipo ordinale. Viene chiesto al rispondente di mappare il proprio grado di accordo o disaccordo con un'affermazione proposta (chiamata 'item').", "kb": "[[Scala Likert]]", "tag": "ium flashcard questionari likert"},
    {"id": "Q054", "tema": "Valutazione Quantitativa", "q": "Un differenziale semantico è...", "a": "Un tipo di scala ordinale in cui l'utente valuta un concetto posizionandolo su una scala compresa tra due aggettivi opposti (es. Bello - Brutto, Complicato - Semplice). Le etichette sono solo agli estremi (ancore).", "kb": "[[AttrakDiff]], [[Questionari psicometrici]]", "tag": "ium flashcard questionari differenziale-semantico"},
    {"id": "Q055", "tema": "Valutazione Quantitativa", "q": "Il central tendency bias è un bias dovuto a...", "a": "La tendenza cognitiva degli utenti di un questionario a preferire i valori o l'opzione centrale della scala (es. 'Né d'accordo né in disaccordo') per pigrizia, evitare di riflettere troppo o non prendere posizioni nette.", "kb": "[[Central tendency bias]]", "tag": "ium flashcard questionari bias"},
    {"id": "Q056", "tema": "Valutazione Quantitativa", "q": "Valutando un NET Promoter Score, quale affermazione è corretta:", "a": "Il valore finale dell'NPS si ottiene sottraendo la percentuale dei detrattori (coloro che hanno votato da 0 a 6) dalla percentuale dei promotori (chi ha votato 9 o 10). I passivi (7-8) sono esclusi dal conteggio finale.", "kb": "[[NPS]]", "tag": "ium flashcard questionari nps"},
    {"id": "Q057", "tema": "Valutazione Quantitativa", "q": "Il NPS (Net Promoter Score) di un prodotto software è...", "a": "Un numero da -100 a +100 che equivale alla percentuale di Promotori meno la percentuale di Detrattori. Misura la loyalty, ovvero la raccomandabilità complessiva di un prodotto, con una singola domanda.", "kb": "[[NPS]]", "tag": "ium flashcard questionari nps"},
    {"id": "Q058", "tema": "Valutazione Quantitativa", "q": "Quando è consigliabile usare un differenziale semantico a sette livelli nella valutazione della dimensione dell'User Experience?", "a": "È lo standard tipico per questionari come l'AttrakDiff, dove è richiesto di posizionare un prodotto tra coppie di aggettivi bipolari a sette intervalli per misurare aspetti pragmatici ed edonici.", "kb": "[[AttrakDiff]]", "tag": "ium flashcard questionari attrakdiff"},
    {"id": "Q059", "tema": "Valutazione Quantitativa", "q": "Nel riportare i dati di un test statistico, quando si denota un valore con un asterisco?", "a": "Nelle convenzioni più comuni: un asterisco (*) indica che il p-value è significativo al livello del 5% (ovvero 0.01 <= p < 0.05). Due asterischi (**) indicano p < 0.01, tre asterischi (***) indicano p < 0.001.", "kb": "[[Significativita statistica e pratica]]", "tag": "ium flashcard statistica p-value"},
    {"id": "Q060", "tema": "Valutazione Quantitativa", "q": "Nella valutazione di un questionario psicometrico la tendenza all'accondiscendenza è...", "a": "L'acquiescence bias: un errore sistematico dovuto alla tendenza di alcuni rispondenti a dirsi 'd'accordo' con le affermazioni del ricercatore per cortesia, disattenzione o per compiacere, a prescindere dal contenuto della domanda.", "kb": "[[Acquiescence bias]], [[Item invertiti]]", "tag": "ium flashcard questionari bias"},
    {"id": "Q061", "tema": "Valutazione Quantitativa", "q": "In uno studio di usabilità, il test statistico di Mann-Whitney è indicato per...", "a": "Identificare se esiste una differenza statisticamente significativa tra due gruppi sperimentali indipendenti (es. chi usa il sistema A e chi usa il B) su dati di tipo ordinale o non distribuiti normalmente.", "kb": "[[Mann-Whitney]]", "tag": "ium flashcard statistica mann-whitney"},
    {"id": "Q062", "tema": "Valutazione Quantitativa", "q": "Indagini campionaria fa...", "a": "Riferimento al processo in cui si analizza un piccolo gruppo (il campione) estratto da un gruppo più vasto. È utile per fare inferenza statistica, ossia desumere informazioni o trarre conclusioni valide per l'intera popolazione originaria.", "kb": "[[Test statistici per IUM]]", "tag": "ium flashcard statistica campione"},
    {"id": "Q063", "tema": "Valutazione Quantitativa", "q": "Quale affermazione è vera sulla valutazione formativa rispetto a quella summativa?", "a": "La formativa viene eseguita durante lo sviluppo iterativo (spesso con metodi qualitativi) per identificare e correggere problemi in corsa. La summativa viene eseguita a prodotto finito per dare un giudizio o misura (quantitativa) di qualità finale.", "kb": "[[Valutazione quantitativa]]", "tag": "ium flashcard usabilita valutazione formativa summativa"},
    {"id": "Q064", "tema": "Valutazione Quantitativa", "q": "Quale affermazione è vera sulle medie delle variabili?", "a": "Si può calcolare (e ha senso logico) la media aritmetica di una variabile quantitativa (a intervalli o a rapporti). Le variabili categoriali usano la moda, quelle ordinali usano tipicamente la mediana, sebbene per i costrutti formati da più item ordinali talvolta si adotti tollerantemente la media.", "kb": "[[Variabili ordinali continue discrete]]", "tag": "ium flashcard statistica variabili"},
    {"id": "Q065", "tema": "Valutazione Quantitativa", "q": "Domanda su A/B test", "a": "L'A/B test è un esperimento randomizzato comparativo con due varianti (A e B), ampiamente usato per quantificare e verificare quale versione massimizza un determinato obiettivo (es. conversion rate). Usa strumenti inferenziali per decidere tra un'ipotesi nulla (le varianti sono uguali) e un'ipotesi alternativa.", "kb": "[[Confronto trasversale]], [[Test statistici per IUM]]", "tag": "ium flashcard statistica ab-test"},
    {"id": "Q066", "tema": "Valutazione Quantitativa", "q": "Un test ABX qual è il numero minimo di volte che è necessario riconoscere x correttamente per concludere che A e B sono diverse tra loro?", "a": "Per N=12 tentativi in una scelta casuale a 2 vie, la probabilità di successo casuale è 0.5. Secondo la distribuzione binomiale, ottenere 10 (o più) successi su 12 ha una probabilità inferiore a 0.05. Quindi servono almeno 10/12 successi per rigettare il caso a un livello alfa 5%.", "kb": "[[Test binomiale]]", "tag": "ium flashcard statistica test-binomiale"},
    {"id": "Q067", "tema": "Valutazione Quantitativa", "q": "Se non abbiamo raccolto un campione di dati tale da non rigettare l'ipotesi nulla, che succede?", "a": "Significa che il p-value calcolato è maggiore del livello di significatività impostato (alfa). Di conseguenza, non vi sono prove sufficienti nel campione per dimostrare che ci siano differenze. Non significa aver provato matematicamente che l'ipotesi nulla sia vera.", "kb": "[[Significativita statistica e pratica]]", "tag": "ium flashcard statistica ipotesi-nulla"},
    {"id": "Q068", "tema": "Valutazione Quantitativa", "q": "Se tre valutatori, ciascuno con la prob. del 70% di trovare un problema, hanno trovato 12 problemi, quanti non sono ancora stati identificati?", "a": "La probabilità che almeno uno lo trovi è 1 - (1-0.7)^3 = 0.973. Se 12 è il 97.3%, il totale stimato è 12/0.973 ≈ 12.33. Quindi i problemi sfuggiti sono circa 0.33, che si arrotonda a 0 problemi interi sfuggiti.", "kb": "[[Valutazione euristica]]", "tag": "ium flashcard valutazione-qualitativa statistica euristiche"},
    {"id": "Q069", "tema": "Valutazione Quantitativa", "q": "Si ottiene un NPS di 10 quando...", "a": "Quando la differenza percentuale tra Promotori e Detrattori è esattamente 10. NON significa che i detrattori sono zero né che l'intero campione sia promotore. Esempio: 20% Promotori e 10% Detrattori dà NPS=10.", "kb": "[[NPS]]", "tag": "ium flashcard questionari nps"},
    {"id": "Q070", "tema": "Valutazione Quantitativa", "q": "Nell'ambito dei test utenti comparativi trasversali, un test binomiale è utile per?", "a": "Testare la significatività statistica quando il dato da analizzare è una scelta binaria o frequenza di successo (es. l'utente preferisce A o B?). Permette di calcolare se lo sbilanciamento di preferenze osservato (es. 10 su 12 preferiscono A) è troppo estremo per essere dettato dal caso.", "kb": "[[Test binomiale]]", "tag": "ium flashcard statistica test-binomiale"},
    {"id": "Q071", "tema": "Valutazione Quantitativa", "q": "Se 2 medie hanno intervalli di confidenza che si sovrappongono appena con 24 utenti, cosa succede aumentando a 48 utenti?", "a": "Aumentando la grandezza del campione (N), l'errore standard diminuisce. Di conseguenza, gli intervalli di confidenza si restringono. Se la differenza media reale è mantenuta, gli intervalli smetteranno di sovrapporsi e la differenza diventerà statisticamente significativa.", "kb": "[[Intervallo di confidenza]], [[Significativita statistica e pratica]]", "tag": "ium flashcard statistica intervalli"},
    {"id": "Q072", "tema": "Valutazione Quantitativa", "q": "Come può essere misurato il fenomeno dello use consistent?", "a": "Il Low Use (o la costanza/ristrettezza d'uso delle funzioni di un sistema) viene calcolato usando uno 'Use Index', in cui si assegna peso pieno (1) alle feature molto usate, mezzo peso a quelle occasionali e peso nullo a quelle inutilizzate.", "kb": "[[Low use]]", "tag": "ium flashcard usabilita use-index"},
    {"id": "Q073", "tema": "Valutazione Quantitativa", "q": "Come si misura il Low Use?", "a": "Attraverso uno Use Index (UI). Se un sistema complesso ha decine di funzioni ma l'utente ne padroneggia e utilizza regolarmente solo una piccola frazione, l'indice sarà basso (<= 0.5), manifestando un forte Low Use e un costo di design inefficace.", "kb": "[[Low use]]", "tag": "ium flashcard usabilita low-use"}
]

with open('exam_prep/domande/domande_note_validate.md', 'a', encoding='utf-8') as fd, \
     open('exam_prep/flashcards/IUM_domande_flashcards.md', 'a', encoding='utf-8') as ff, \
     open('exam_prep/flashcards/IUM_domande_flashcards_anki.tsv', 'a', encoding='utf-8') as fa:

    for item in data:
        fd.write(f"## {item['id']} — {item['tema']}\n\n")
        fd.write(f"> [!Question]\n> {item['q']}\n\n")
        
        # Validazione manuale o check speciale per stati
        if item['id'] == 'Q072':
            fd.write(f"**Risposta validata:**  \n{item['a']}\n\n")
            fd.write("**Stato:** da verificare (nomenclatura 'use consistent' ambigua, riferito al Low Use)\n\n")
        else:
            fd.write(f"**Risposta validata:**  \n{item['a']}\n\n")
            fd.write(f"**Stato:** validata\n\n")
            
        fd.write(f"**Note KB collegate:**\n")
        for kb in item['kb'].split(", "):
            fd.write(f"- {kb}\n")
        fd.write("---\n\n")

        ff.write(f"## FC-{item['id']} — {item['tema']}\n\n")
        ff.write(f"**Domanda**  \n{item['q']}\n\n")
        ff.write(f"**Risposta**  \n{item['a']}\n\n")
        ff.write(f"**Tag:** {' '.join(['#'+t for t in item['tag'].split()])}\n\n---\n\n")

        q_br = item['q'].replace('\n', '<br>')
        a_br = item['a'].replace('\n', '<br>')
        fa.write(f"{item['id']}\t{q_br}\t{a_br}\t{item['tag']}\n")

print("Chunk 3 written successfully.")
